import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"]
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="bg-gradient-to-b from-zinc-950 to-zinc-900"
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen w-full bg-gradient-to-b from-zinc-950 to-zinc-900 overflow-x-hidden`}
      >
        {/* Decorative elements */}
        <div className="fixed -top-20 -left-20 w-64 h-64 bg-rose-500/5 rounded-full blur-3xl"></div>
        <div className="fixed -bottom-20 -right-20 w-64 h-64 bg-blue-500/5 rounded-full blur-3xl"></div>

        <Providers>
          <main className="h-full w-full">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
